yaml

name: hello-world
on: push

jobs:
  hello-world-job:

    runs-on : ubuntu-latest

  Steps:
    - name: Check out repository code
      user: actions/checkout@v3
    -run: echo "$(cat hello_world.txt)"
